// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsaOB0_Cl9klzFi7br4hfu0O4EUc0xnls',
    appId: '1:130288048694:web:bd678b68ebfc6fe3c29697',
    messagingSenderId: '130288048694',
    projectId: 'aurafarm-cec55',
    authDomain: 'aurafarm-cec55.firebaseapp.com',
    storageBucket: 'aurafarm-cec55.firebasestorage.app',
    measurementId: 'G-FYJWY1VZLY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUk1C0KW8H13F4DdvA0dIYhY5g_g8zaEw',
    appId: '1:130288048694:android:b21714cfe1d4b43cc29697',
    messagingSenderId: '130288048694',
    projectId: 'aurafarm-cec55',
    storageBucket: 'aurafarm-cec55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBImnRrg4l-RHdRUkv9FSFoQCv_Qdt7pn8',
    appId: '1:130288048694:ios:8aa26a71cbcc5984c29697',
    messagingSenderId: '130288048694',
    projectId: 'aurafarm-cec55',
    storageBucket: 'aurafarm-cec55.firebasestorage.app',
    iosBundleId: 'com.aura.uganda.auraApp',
  );
}
